// HBCU institutions for the "HBCU Alma Mater" signup dropdown.
// Source: HBCU_Institutions_List.xlsx provided by Dana (2026-08).
// Note: the spreadsheet listed "Lincoln University of Missouri" twice; deduplicated here.
export const HBCU_INSTITUTIONS = [
  "None",
  "Alabama A&M University",
  "Alabama State University",
  "Albany State University",
  "Alcorn State University",
  "Allen University",
  "American Baptist College",
  "Arkansas Baptist College",
  "Benedict College",
  "Bennett College",
  "Bethune-Cookman University",
  "Bluefield State University",
  "Bowie State University",
  "Central State University",
  "Cheyney University of Pennsylvania",
  "Claflin University",
  "Clark Atlanta University",
  "Clinton College",
  "Coppin State University",
  "Delaware State University",
  "Denmark Technical College",
  "Dillard University",
  "Edward Waters University",
  "Elizabeth City State University",
  "Fayetteville State University",
  "Fisk University",
  "Florida A&M University",
  "Florida Memorial University",
  "Fort Valley State University",
  "Grambling State University",
  "Hampton University",
  "Harris-Stowe State University",
  "Howard University",
  "Huston-Tillotson University",
  "Interdenominational Theological Center",
  "Jackson State University",
  "Jarvis Christian University",
  "Johnson C. Smith University",
  "Kentucky State University",
  "Lane College",
  "Langston University",
  "LeMoyne-Owen College",
  "Lincoln University of Missouri",
  "Livingstone College",
  "Meharry Medical College",
  "Miles College",
  "Mississippi Valley State University",
  "Morehouse College",
  "Morehouse School of Medicine",
  "Morgan State University",
  "Morris Brown College",
  "Morris College",
  "Norfolk State University",
  "North Carolina A&T State University",
  "North Carolina Central University",
  "Oakwood University",
  "Paine College",
  "Paul Quinn College",
  "Philander Smith University",
  "Prairie View A&M University",
  "Rust College",
  "Saint Augustine's University",
  "Savannah State University",
  "Shaw University",
  "Shorter College",
  "Simmons College of Kentucky",
  "South Carolina State University",
  "Southern University and A&M College",
  "Southwestern Christian College",
  "Spelman College",
  "St. Philip's College",
  "Stillman College",
  "Talladega College",
  "Tennessee State University",
  "Texas College",
  "Texas Southern University",
  "Tougaloo College",
  "Tuskegee University",
  "University of Arkansas at Pine Bluff",
  "University of Maryland Eastern Shore",
  "University of the District of Columbia",
  "University of the Virgin Islands",
  "Virginia State University",
  "Virginia Union University",
  "Virginia University of Lynchburg",
  "Voorhees University",
  "West Virginia State University",
  "Wilberforce University",
  "Wiley University (formerly Wiley College)",
  "Winston-Salem State University",
  "Xavier University of Louisiana",
];
