// Module quiz data extracted from Dana's LBCI Masterclass quiz documents
// Each module has 20 multiple-choice questions with 4 options (A-D)
// Pass threshold: 80% (16/20 correct)

export interface QuizQuestion {
  id: number;
  lessonRef: string;
  question: string;
  options: { label: string; text: string }[];
  correctAnswer: string;
}

export interface ModuleQuiz {
  moduleNumber: number;
  title: string;
  questions: QuizQuestion[];
  passThreshold: number; // percentage
}

export const MODULE_QUIZZES: ModuleQuiz[] = [
  {
    moduleNumber: 1,
    title: "The Value of Illuminating Workplace Problems",
    passThreshold: 80,
    questions: [
      {
        id: 1,
        lessonRef: "Lesson 1",
        question: "Sarah is a middle manager who consistently meets her department\u2019s targets and receives positive performance reviews. However, she was passed over for promotion to director for the third time. Based on this lesson, what is the MOST likely reason?",
        options: [
          { label: "A", text: "She lacks the technical skills required for a director position" },
          { label: "B", text: "She has not demonstrated measurable improvement initiatives or strategic problem-solving capabilities" },
          { label: "C", text: "She does not have enough years of experience in her current role" },
          { label: "D", text: "Her team performance metrics are not strong enough for promotion" },
        ],
        correctAnswer: "B",
      },
      {
        id: 2,
        lessonRef: "Lesson 1",
        question: "Marcus spends most of his day handling urgent issues: fixing errors, responding to complaints, and coordinating between departments. Despite working 50+ hours weekly, his manager says he needs to \u201Cdemonstrate more strategic impact.\u201D According to this lesson, what should Marcus do FIRST?",
        options: [
          { label: "A", text: "Work even longer hours to prove his dedication and commitment" },
          { label: "B", text: "Delegate more tasks to his team so he has time for strategic projects" },
          { label: "C", text: "Learn to identify and systematically eliminate the root causes creating these daily urgent issues" },
          { label: "D", text: "Ask his manager to assign him to a strategic project team" },
        ],
        correctAnswer: "C",
      },
      {
        id: 3,
        lessonRef: "Lesson 2",
        question: "Jennifer\u2019s team experiences frequent errors in account reconciliations requiring significant rework time. She immediately proposes implementing a new automated reconciliation system she read about in an industry journal. According to the CI Done Right Formula taught in this lesson, what should Jennifer do FIRST before proposing this solution?",
        options: [
          { label: "A", text: "Intelligently Test the new system with a small pilot group to see if it reduces errors" },
          { label: "B", text: "Illuminate the problem by documenting current error rates and Investigate root causes of why errors occur" },
          { label: "C", text: "Implement the new system department-wide since automation generally improves accuracy" },
          { label: "D", text: "Skip to Implementation since she already knows what solution will work" },
        ],
        correctAnswer: "B",
      },
      {
        id: 4,
        lessonRef: "Lesson 2",
        question: "David completed a root cause investigation showing that customer service wait times were high because agents spent excessive time searching for account information across three different systems. He designed a solution consolidating data into one interface. According to the CI Done Right Formula, what should David\u2019s NEXT step be?",
        options: [
          { label: "A", text: "Immediately Implement the consolidated interface across all 50 customer service agents" },
          { label: "B", text: "Illuminate additional problems in the customer service process before addressing this one" },
          { label: "C", text: "Intelligently Test the consolidated interface with 5-10 agents for 2-4 weeks to validate it reduces wait times" },
          { label: "D", text: "Investigate whether there are other root causes beyond the three-system issue" },
        ],
        correctAnswer: "C",
      },
      {
        id: 5,
        lessonRef: "Lesson 3",
        question: "Maria notices that her team\u2019s financial analysts spend 90 minutes each morning manually downloading data from five different systems, copying it into Excel, and reformatting it before they can begin their actual analysis work. Which TIMWOODI waste type does this PRIMARILY represent?",
        options: [
          { label: "A", text: "Transportation waste, because data is moving between systems" },
          { label: "B", text: "Motion waste, because employees are making excessive clicks and keystrokes" },
          { label: "C", text: "Waiting waste, because analysis can\u2019t begin until data is prepared" },
          { label: "D", text: "Intellect waste, because skilled analysts are doing low-value data preparation work" },
        ],
        correctAnswer: "D",
      },
      {
        id: 6,
        lessonRef: "Lesson 3",
        question: "James discovers that his department generates a comprehensive 40-page monthly performance report with detailed analysis and charts. However, when he asks executives if they read it, he learns that only the 2-page executive summary gets reviewed\u2014the other 38 pages are never opened. Which waste type should James focus on eliminating?",
        options: [
          { label: "A", text: "Defects waste, because the report contains unnecessary information" },
          { label: "B", text: "Overproduction waste, because 38 pages of work is being produced that nobody needs" },
          { label: "C", text: "Overprocessing waste, because too much detail is being provided" },
          { label: "D", text: "Waiting waste, because creating the report delays other work" },
        ],
        correctAnswer: "B",
      },
      {
        id: 7,
        lessonRef: "Lesson 4",
        question: "You\u2019ve identified two improvement opportunities:\nOpportunity X eliminates waste costing $200,000 annually but requires 16 weeks, IT system integration, and executive sponsorship across three departments. Opportunity Y eliminates waste costing $12,000 annually but can be implemented in 3 weeks with only your team\u2019s involvement and no budget required. You\u2019ve never led a continuous improvement initiative before. According to the PICK Chart framework and strategic prioritization principles taught in this lesson, what should you do?",
        options: [
          { label: "A", text: "Pursue Opportunity X first because the $200K impact will prove your strategic value faster" },
          { label: "B", text: "Pursue Opportunity Y first to build credibility and CI skills, then tackle Opportunity X as your first Waste WAR Battle" },
          { label: "C", text: "Pursue both simultaneously to maximize total impact and demonstrate your ability to manage multiple priorities" },
          { label: "D", text: "Ask your manager to decide which opportunity you should pursue first" },
        ],
        correctAnswer: "B",
      },
      {
        id: 8,
        lessonRef: "Lesson 4",
        question: "During prioritization, your team identifies an improvement opportunity that would save approximately $8,000 annually and requires working with IT to modify a system integration\u2014a process that historically takes 9-12 months due to IT\u2019s project backlog. Where should this opportunity be plotted on the PICK Chart, and what action should you take?",
        options: [
          { label: "A", text: "Implement quadrant; pursue immediately because $8K annual savings compounds over time" },
          { label: "B", text: "Challenge quadrant; pursue as a Waste WAR Battle because it requires sustained effort" },
          { label: "C", text: "Possible quadrant; pursue only if IT capacity becomes available unexpectedly" },
          { label: "D", text: "Kill quadrant; avoid entirely because long implementation timeline and low impact make ROI unacceptable" },
        ],
        correctAnswer: "D",
      },
      {
        id: 9,
        lessonRef: "Lesson 5",
        question: "A manager creating a SIPOC diagram for her department\u2019s monthly reporting process lists 35 detailed process steps including specific mouse clicks, individual data fields entered, and every email sent during report creation. According to SIPOC best practices taught in this lesson, what should she do?",
        options: [
          { label: "A", text: "Continue with the detailed approach because comprehensive documentation ensures nothing is missed" },
          { label: "B", text: "Reduce the Process column to 5-10 high-level steps by combining detailed activities into logical groupings" },
          { label: "C", text: "Move the detailed steps to the Inputs column since they represent information needed for the process" },
          { label: "D", text: "Create separate SIPOC diagrams for each subprocess to maintain the current level of detail" },
        ],
        correctAnswer: "B",
      },
      {
        id: 10,
        lessonRef: "Lesson 5",
        question: "While creating a SIPOC for his loan processing workflow, Marcus identifies these customers: \u201CCustomers who applied for loans, other people in the department, and some folks in other departments.\u201D According to SIPOC best practices, what\u2019s the PRIMARY problem with Marcus\u2019s customer identification?",
        options: [
          { label: "A", text: "He didn\u2019t distinguish between internal and external customers" },
          { label: "B", text: "His descriptions are too vague and lack specificity about who exactly receives process outputs" },
          { label: "C", text: "He listed too many customer groups for a single process" },
          { label: "D", text: "He should have listed customers before identifying process steps" },
        ],
        correctAnswer: "B",
      },
      {
        id: 11,
        lessonRef: "Lesson 6",
        question: "A manager writes this problem statement: \u201COur department has efficiency problems that are costing us money and frustrating our team. We\u2019ve noticed that processes take longer than they should and customers aren\u2019t happy with our service. We should work on improving things because this has been going on for years.\u201D According to the six-element problem statement formula taught in this lesson, what is the PRIMARY weakness?",
        options: [
          { label: "A", text: "The statement doesn\u2019t identify any root causes" },
          { label: "B", text: "The statement lacks specificity in all six elements\u2014no context detail, no waste type identified, no quantified impact, no specific stakeholders, no compelling urgency" },
          { label: "C", text: "The statement is too long and should be more concise" },
          { label: "D", text: "The statement doesn\u2019t mention which SIPOC diagram was used" },
        ],
        correctAnswer: "B",
      },
      {
        id: 12,
        lessonRef: "Lesson 6",
        question: "Sarah created a SIPOC diagram for her customer service process and identified $95,000 annual waste through PICK Chart analysis. When writing her problem statement, she includes detailed root cause analysis explaining exactly why the waste exists with high certainty. According to this lesson\u2019s guidance on the Root Cause Indication element, what should Sarah do instead?",
        options: [
          { label: "A", text: "Include the detailed root cause analysis since thorough understanding demonstrates competence" },
          { label: "B", text: "Omit root causes entirely since Module 2 will investigate them" },
          { label: "C", text: "Share preliminary observations about potential root causes while acknowledging deep investigation will occur during the Waste WAR Battle" },
          { label: "D", text: "Wait to write the problem statement until after completing Module 2\u2019s root cause investigation" },
        ],
        correctAnswer: "C",
      },
      {
        id: 13,
        lessonRef: "Lesson 7",
        question: "During Week 3 of the 30-day plan, you\u2019re reviewing team members\u2019 submitted SIPOC diagrams and problem statements. One team member\u2019s work has significant gaps\u2014missing stakeholders in the SIPOC, no quantified impact in the problem statement. According to this lesson\u2019s facilitation guidance, what should you do?",
        options: [
          { label: "A", text: "Provide direct critical feedback pointing out all the errors so the team member learns proper technique" },
          { label: "B", text: "Focus feedback on what they did well, offer one gentle suggestion for improvement, and invite peer input on the work" },
          { label: "C", text: "Skip reviewing this person\u2019s work to avoid embarrassing them in front of the team" },
          { label: "D", text: "Have a private conversation after the meeting to provide detailed correction before showing their work to the team" },
        ],
        correctAnswer: "B",
      },
      {
        id: 14,
        lessonRef: "Lesson 7",
        question: "During Week 4, your team uses the PICK Chart to prioritize improvement opportunities. Several team members strongly prefer working on a problem that plots in the \u201CPossible\u201D quadrant (low impact, low effort) because it feels \u201Cachievable and low-risk.\u201D You know from Lesson 4 that Possible quadrant problems should generally be avoided for first Waste WAR Battles. According to this lesson\u2019s guidance, what should you do?",
        options: [
          { label: "A", text: "Override the team\u2019s preference and assign the high-impact problem you know is better, explaining they\u2019ll understand your decision later" },
          { label: "B", text: "Let the team select the Possible quadrant problem to build engagement even though it won\u2019t deliver significant results" },
          { label: "C", text: "Facilitate discussion about impact vs. effort trade-offs, share why high-impact problems deliver better career value, and guide team toward Implement quadrant selection" },
          { label: "D", text: "Postpone the selection decision until next week when team might be more receptive to high-impact choices" },
        ],
        correctAnswer: "C",
      },
      {
        id: 15,
        lessonRef: "Module 1 General Knowledge",
        question: "After completing Module 1, you\u2019ve learned TIMWOODI waste identification, PICK Chart prioritization, SIPOC mapping, and problem statement development. A colleague asks, \u201CWhat\u2019s the overall purpose of Module 1 in the CI Done Right Formula?\u201D According to the module\u2019s comprehensive teaching, what should you answer?",
        options: [
          { label: "A", text: "Module 1 teaches how to investigate root causes systematically so you can find solutions faster" },
          { label: "B", text: "Module 1 teaches how to test potential solutions to validate they work before full implementation" },
          { label: "C", text: "Module 1 teaches how to illuminate workplace problems by identifying waste, prioritizing opportunities, mapping current state, and articulating compelling problem statements that position you as strategic problem-solver" },
          { label: "D", text: "Module 1 teaches how to implement winning solutions and share results with stakeholders" },
        ],
        correctAnswer: "C",
      },
      {
        id: 16,
        lessonRef: "Module 1 General Knowledge",
        question: "You\u2019ve completed all Module 1 lessons and want to explain the CI Done Right Formula\u2019s competitive advantage to a skeptical peer manager who says, \u201CI already know how to solve problems\u2014I just fix them when they come up. Why do I need a four-step formula?\u201D Based on Module 1\u2019s teaching, what\u2019s the BEST response emphasizing systematic methodology value?",
        options: [
          { label: "A", text: "The formula helps you work faster so you can fix more problems in less time" },
          { label: "B", text: "The formula transforms reactive firefighting into strategic problem-solving that\u2019s measurable, sustainable, and positions you for promotion\u2014most managers solve symptoms temporarily while the formula eliminates root causes permanently with documented results proving your strategic value" },
          { label: "C", text: "The formula is required by most Fortune 500 companies so learning it makes you more employable" },
          { label: "D", text: "The formula helps you delegate problem-solving to your team members so you have more time for strategic work" },
        ],
        correctAnswer: "B",
      },
      {
        id: 17,
        lessonRef: "Module 1 General Knowledge",
        question: "During your first 30 days applying Module 1 content, you facilitate weekly team meetings where members share SIPOC diagrams and problem statements. Several team members initially submit work with significant gaps, but you provide positive feedback on what they did well and gentle suggestions for improvement. By Week 4, the team\u2019s work quality has dramatically improved and engagement is high. This outcome demonstrates which Module 1 principle?",
        options: [
          { label: "A", text: "PICK Chart prioritization ensures teams focus on high-impact problems generating quick wins" },
          { label: "B", text: "SIPOC mapping quality improves naturally as teams practice the five-column framework" },
          { label: "C", text: "Positive facilitation approach building psychological safety enables team capability development and sustained engagement better than critical feedback emphasizing errors" },
          { label: "D", text: "Problem statement six-element formula provides structure ensuring completeness and consistency" },
        ],
        correctAnswer: "C",
      },
      {
        id: 18,
        lessonRef: "Module 1 General Knowledge",
        question: "Six months after completing Module 1, you\u2019ve successfully executed the 30-day plan, identified $250,000 in annual waste through TIMWOODI analysis, prioritized three high-impact problems using PICK Charts, created detailed SIPOC diagrams, and written compelling problem statements. Your manager asks, \u201CWhat should you do next with these documented opportunities?\u201D Based on the CI Done Right Formula taught in Module 1, what\u2019s the correct answer?",
        options: [
          { label: "A", text: "Immediately implement solutions to the three prioritized problems since you\u2019ve already invested significant time in analysis" },
          { label: "B", text: "Share the problem statements with senior leadership to demonstrate your strategic thinking and request resources for solutions" },
          { label: "C", text: "Repeat Module 1 activities to identify additional waste opportunities before addressing the current three problems" },
          { label: "D", text: "Progress to Module 2 (Investigating Root Causes for Success) to systematically determine why the three prioritized problems exist before jumping to solutions" },
        ],
        correctAnswer: "D",
      },
      {
        id: 19,
        lessonRef: "Module 1 General Knowledge",
        question: "You\u2019ve just completed Module 1 and documented several TIMWOODI waste instances costing your department approximately $180,000 annually. Your boss asks, \u201CHow does identifying this waste actually help your career advancement?\u201D Based on Module 1\u2019s comprehensive teaching across all seven lessons, what\u2019s the MOST accurate answer?",
        options: [
          { label: "A", text: "Identifying waste demonstrates attention to detail and thorough analysis skills leadership values" },
          { label: "B", text: "Documenting waste problems shows you\u2019re proactive about finding issues before they become crises" },
          { label: "C", text: "Waste identification proves you understand financial impact and can speak leadership\u2019s language about cost savings" },
          { label: "D", text: "Systematically identifying, quantifying, and prioritizing waste transforms you from reactive firefighter to strategic problem-solver with documented evidence of organizational value creation\u2014the measurable improvement capability that distinguishes promotable managers from those who plateau" },
        ],
        correctAnswer: "D",
      },
      {
        id: 20,
        lessonRef: "Module 1 General Knowledge",
        question: "Three months after completing Module 1\u2019s 30-day plan, you notice your team has stopped conducting weekly waste identification exercises, SIPOC diagrams are no longer being updated, and the improvement momentum has faded despite initial enthusiasm. According to Module 1\u2019s teaching and the broader CI Done Right methodology, what\u2019s the PRIMARY reason this regression occurred and what should you do?",
        options: [
          { label: "A", text: "The team lost interest because continuous improvement work is inherently tedious; restart with different team members who are more naturally motivated" },
          { label: "B", text: "You selected the wrong initial problems to address; re-do the PICK Chart prioritization choosing more engaging opportunities" },
          { label: "C", text: "The 30-day plan was too aggressive; scale back to monthly instead of weekly activities to prevent team burnout" },
          { label: "D", text: "Module 1 illumination activities aren\u2019t self-sustaining without systematic culture reinforcement\u2014you need Module 4\u2019s Culture Reinforcement System (daily exercises, weekly check-ins, monthly celebrations) making improvement habitual rather than episodic project; lack of reinforcement causes all improvement initiatives to fade regardless of initial enthusiasm" },
        ],
        correctAnswer: "D",
      },
    ],
  },
  {
    moduleNumber: 2,
    title: "Investigating Root Causes for Success",
    passThreshold: 80,
    questions: [
      {
        id: 1,
        lessonRef: "Lesson 1",
        question: "A manager who completed Module 1 has identified a high-impact waste opportunity and written a problem statement. She\u2019s eager to start fixing the problem immediately and asks: \u201CWhy do I need to spend 6 sessions (Steps 1-4) investigating before I can start brainstorming solutions in Sessions 8-9? Can\u2019t I skip to Step 6 since I already know what the problem is?\u201D According to this lesson\u2019s explanation of why the Waste WAR Battle succeeds, what is the BEST response?",
        options: [
          { label: "A", text: "You\u2019re right\u2014if the problem is obvious, you can skip Steps 1-4 and jump directly to brainstorming solutions to save time" },
          { label: "B", text: "Steps 1-4 investigation ensures you understand root causes, not just symptoms, because solutions addressing causes succeed 90% of the time versus 30% when skipping investigation" },
          { label: "C", text: "The 14-session structure is required by the methodology and cannot be modified regardless of circumstances" },
          { label: "D", text: "You should complete Steps 1-4 to build team engagement even though investigation probably won\u2019t reveal anything new" },
        ],
        correctAnswer: "B",
      },
      {
        id: 2,
        lessonRef: "Lesson 1",
        question: "During Session 13 of a Waste WAR Battle, the team has tested three potential solutions through pilots (Step 7). One solution showed 40% improvement in the target metric during the pilot. The manager says: \u201CThis solution clearly works\u2014let\u2019s implement it fully across the entire department immediately and skip Session 14 planning since we\u2019ve already proven success.\u201D According to the 10-step system taught in this lesson, what should happen instead?",
        options: [
          { label: "A", text: "Agree and implement immediately since 40% improvement is proven" },
          { label: "B", text: "Complete Session 14 for proper implementation planning, Control Plans, and sustainability measures" },
          { label: "C", text: "Learn to identify and systematically eliminate the root causes creating these daily urgent issues" },
          { label: "D", text: "Ask his manager to assign him to a strategic project team" },
        ],
        correctAnswer: "C",
      },
      {
        id: 3,
        lessonRef: "Lesson 2",
        question: "During your Waste WAR Battle Session #1, a team member says: \u201CWhile we\u2019re fixing the underwriting queue delays, we should also redesign the application intake form, update the tracking system, and improve our loan officer training program. These all contribute to slow processing.\u201D According to this lesson\u2019s guidance on avoiding common pitfalls, what should you do as the facilitator?",
        options: [
          { label: "A", text: "Agree to expand the scope since all these improvements are related and addressing them together will be more efficient" },
          { label: "B", text: "Acknowledge the additional opportunities, document them in a parking lot for future consideration, and refocus the team on the original defined scope" },
          { label: "C", text: "Take a vote among team members to decide whether to expand the scope or stay focused" },
          { label: "D", text: "End Session #1 and reschedule after deciding whether to include these additional improvements" },
        ],
        correctAnswer: "B",
      },
      {
        id: 4,
        lessonRef: "Lesson 2",
        question: "You\u2019ve completed Session #1 and drafted this opportunity statement with your team: \u201CWe will improve our customer service processes to enhance customer satisfaction and reduce costs.\u201D Based on the five-element opportunity statement framework taught in this lesson, what is the PRIMARY problem with this statement?",
        options: [
          { label: "A", text: "It doesn\u2019t identify who will be on the Waste WAR Battle team" },
          { label: "B", text: "It lacks all five required elements\u2014no specific waste type, no quantified impact, no affected stakeholders, no urgency rationale, and no scope boundaries" },
          { label: "C", text: "It should include specific solution ideas the team will test" },
          { label: "D", text: "It needs approval from senior leadership before being finalized" },
        ],
        correctAnswer: "B",
      },
      {
        id: 5,
        lessonRef: "Lesson 3",
        question: "During Session #2 metric brainstorming, your team suggests tracking these four potential metrics: (1) \u201CNumber of improvement team meetings held,\u201D (2) \u201CHours team members invested in process analysis,\u201D (3) \u201CPercentage of team who feel processes improved,\u201D (4) \u201CAverage loan processing cycle time reduction.\u201D According to the vanity metrics vs. value metrics distinction taught in this lesson, which of these represents a VALUE metric that demonstrates business impact?",
        options: [
          { label: "A", text: "Metrics 1 and 2 because they quantify team investment and effort" },
          { label: "B", text: "Metric 3 because team perception matters for engagement and morale" },
          { label: "C", text: "Metric 4 because it quantifies a business outcome leadership cares about" },
          { label: "D", text: "All four metrics are valuable and should be tracked together for comprehensive measurement" },
        ],
        correctAnswer: "C",
      },
      {
        id: 6,
        lessonRef: "Lesson 3",
        question: "Your team plotted five brainstormed metrics on the PICK Chart with axes Measurability (vertical) and Relevance (horizontal). Results: Metric A = high measurability, high relevance (Implement quadrant). Metric B = high measurability, low relevance (Possible quadrant). Metric C = low measurability, high relevance (Challenge quadrant). Metric D = low measurability, low relevance (Kill quadrant). Metric E = high measurability, high relevance (Implement quadrant). According to this lesson\u2019s PICK Chart selection guidance, which metric(s) should the team select?",
        options: [
          { label: "A", text: "Select all five metrics for comprehensive measurement across multiple dimensions" },
          { label: "B", text: "Select Metrics A and E only since they\u2019re both in Implement quadrant (measurable and relevant)" },
          { label: "C", text: "Select Metric C because high relevance matters most even if measurement is difficult" },
          { label: "D", text: "Select Metric B because high measurability ensures you can definitely track it" },
        ],
        correctAnswer: "B",
      },
      {
        id: 7,
        lessonRef: "Lesson 4",
        question: "During Session #3 direct observation of a loan underwriting process, a team member observes that applications sit in the queue 3-5 days before review begins and immediately says: \u201CThis is ridiculous! We should implement automated routing that assigns applications to underwriters immediately when they arrive in the queue!\u201D According to this lesson\u2019s guidance on Session #3 facilitation, how should you respond as the facilitator?",
        options: [
          { label: "A", text: "Agree with the suggestion and pause observation to discuss implementation details since the solution is obviously beneficial" },
          { label: "B", text: "Acknowledge the observation of queue delays, document it as important data, and redirect the team to continue observing without proposing solutions yet since root cause analysis comes in Sessions 5-6" },
          { label: "C", text: "Disagree with the suggestion explaining that automated routing might not address the actual root cause" },
          { label: "D", text: "Ask the team to vote on whether they agree with the proposed solution before deciding whether to continue observation" },
        ],
        correctAnswer: "B",
      },
      {
        id: 8,
        lessonRef: "Lesson 4",
        question: "Your team is preparing for Session #3 to observe a customer onboarding process that happens primarily through electronic systems. The process involves three different software applications where employees enter data, review information, and route approvals. According to this lesson\u2019s guidance on electronic process observation techniques, what is the BEST approach for Session #3?",
        options: [
          { label: "A", text: "Have each team member individually log into the systems and practice the workflow themselves to understand it fully" },
          { label: "B", text: "Review the system training manual together as a team to understand the documented workflow before observing" },
          { label: "C", text: "Have an experienced employee demonstrate the complete workflow while projecting their screen so the entire team observes simultaneously, with the employee using their actual system (not a training environment) and talking through each step" },
          { label: "D", text: "Ask IT to provide a recorded video of the process that the team can watch together" },
        ],
        correctAnswer: "C",
      },
      {
        id: 9,
        lessonRef: "Lesson 5",
        question: "During Session #4, as your team creates the Current State Process Flow Map, several team members start commenting on pain points they observe: \u201CThis handoff always creates errors!\u201D \u201CThis delay is ridiculous!\u201D \u201CThis approval step is pure waste!\u201D According to this lesson\u2019s guidance on Session #4 facilitation, how should you respond?",
        options: [
          { label: "A", text: "Immediately add pain point annotations to the map since the team is identifying them organically" },
          { label: "B", text: "Acknowledge the insights, explain that Session #5 will capture all pain points with expanded stakeholder input including customers, and redirect the team to continue mapping the process accurately without adding pain points yet" },
          { label: "C", text: "Stop the mapping work and transition to pain point identification since the team is engaged" },
          { label: "D", text: "Ignore the comments and continue mapping without acknowledging them" },
        ],
        correctAnswer: "B",
      },
      {
        id: 10,
        lessonRef: "Lesson 5",
        question: "Your team has completed the Session #4 Current State Process Flow Map showing all process steps, handoffs, and delays observed during Session #3. You\u2019re now planning Session #5 stakeholder invitations. According to this lesson\u2019s emphasis on Voice of Customer, which of the following stakeholder groups should you prioritize inviting to Session #5?",
        options: [
          { label: "A", text: "Additional members of the core Waste WAR Battle team who didn\u2019t attend Session #4" },
          { label: "B", text: "Senior leadership who approve improvement initiatives" },
          { label: "C", text: "Customers who recently experienced the process and can identify pain points from their perspective" },
          { label: "D", text: "Continuous improvement consultants who can provide expert guidance" },
        ],
        correctAnswer: "C",
      },
      {
        id: 11,
        lessonRef: "Lesson 6",
        question: "During Session #5 pain point identification with your expanded stakeholder group (12-15 people), participants start debating whether a particular pain point is \u201Csignificant enough\u201D to add to the process map. Some say it\u2019s minor, others say it\u2019s major. According to this lesson\u2019s guidance on Session #5 facilitation, how should you respond?",
        options: [
          { label: "A", text: "Take a vote and only add the pain point if majority agrees it\u2019s significant" },
          { label: "B", text: "Capture the pain point now without filtering or debating significance, explaining that PICK Chart prioritization in minutes 70-90 will determine which pain points get root cause investigation" },
          { label: "C", text: "Ask senior leadership to decide whether the pain point is significant enough" },
          { label: "D", text: "Skip the pain point since there\u2019s disagreement about its importance" },
        ],
        correctAnswer: "B",
      },
      {
        id: 12,
        lessonRef: "Lesson 6",
        question: "Your team has identified and documented 28 pain points during Session #5. During PICK Chart prioritization (minutes 70-90), several team members argue: \u201CAll 28 pain points are important! We should investigate root causes for all of them in Session #6!\u201D According to this lesson\u2019s teaching about pain point prioritization, what is the BEST response?",
        options: [
          { label: "A", text: "Agree to investigate all 28 pain points since they were all identified by stakeholders" },
          { label: "B", text: "Explain that Session #6 has 90 minutes, and investigating 5-6 pain points thoroughly produces better root cause understanding than investigating 28 pain points superficially; select 5-6 from Implement quadrant (high impact, low effort)" },
          { label: "C", text: "Split the team into sub-groups with each group investigating different pain points simultaneously" },
          { label: "D", text: "Extend Session #6 to 3 hours to accommodate investigating all pain points" },
        ],
        correctAnswer: "B",
      },
      {
        id: 13,
        lessonRef: "Lesson 7",
        question: "During Session #6 Cause Tree Analysis for the pain point \u201CApplications wait in queue 3-5 days,\u201D your team identifies \u201Cbatch processing approach\u201D as a first-level cause. When you ask \u201CWhy batch processing approach?\u201D, a team member responds: \u201CBecause that\u2019s how we\u2019ve always done it.\u201D According to this lesson\u2019s teaching on root cause investigation, what should you do next?",
        options: [
          { label: "A", text: "Accept \u201Chow we\u2019ve always done it\u201D as the root cause and move to the next pain point" },
          { label: "B", text: "Continue drilling deeper by asking \u201CWhy have we always done it that way?\u201D to investigate second-level causes underneath the historical practice explanation" },
          { label: "C", text: "Skip this cause and focus on other first-level causes that seem more important" },
          { label: "D", text: "Immediately brainstorm solutions for changing the batch processing approach" },
        ],
        correctAnswer: "B",
      },
      {
        id: 14,
        lessonRef: "Lesson 7",
        question: "Your team has completed Cause Tree Analysis for all 5-6 prioritized pain points, identifying 42 total root causes across all the cause trees. During PICK Chart prioritization (minutes 75-90), several team members argue: \u201CWe should brainstorm solutions for all 42 root causes since we invested effort identifying them!\u201D According to this lesson\u2019s teaching about root cause prioritization, what is the BEST response?",
        options: [
          { label: "A", text: "Agree to address all 42 root causes to maximize improvement impact" },
          { label: "B", text: "Explain that Sessions #7-13 provide approximately 79 minutes per root cause when focusing on 8, versus 14 minutes per root cause if spread across 42; select maximum 8 from Implement quadrant (high impact, low complexity) enabling thorough solution development" },
          { label: "C", text: "Compromise by selecting 20 root causes as middle ground between 8 and 42" },
          { label: "D", text: "Extend Sessions #7-13 to accommodate all 42 root causes" },
        ],
        correctAnswer: "B",
      },
      {
        id: 15,
        lessonRef: "Module 2 General Knowledge",
        question: "After completing Module 2, you understand the complete investigation phase of the CI Done Right Formula. A colleague who just completed Module 1 asks: \u201CWhat\u2019s the main difference between Module 1 (Illuminating Problems) and Module 2 (Investigating Root Causes)?\u201D Based on Module 2\u2019s comprehensive teaching, what\u2019s the BEST answer?",
        options: [
          { label: "A", text: "Module 1 focuses on external customer problems while Module 2 focuses on internal process problems" },
          { label: "B", text: "Module 1 requires team participation while Module 2 is completed by the manager alone" },
          { label: "C", text: "Module 1 identifies WHAT problems exist and prioritizes them (TIMWOODI waste, PICK Charts, problem statements), while Module 2 investigates WHY problems exist through systematic 6-session root cause analysis (defining metrics, confirming current state, identifying pain points, determining root causes) before jumping to solutions" },
          { label: "D", text: "Module 1 teaches theoretical concepts while Module 2 focuses on practical implementation" },
        ],
        correctAnswer: "C",
      },
      {
        id: 16,
        lessonRef: "Module 2 General Knowledge",
        question: "Six months after completing your first Waste WAR Battle using Module 2\u2019s investigation methodology, you notice that the improvements have sustained and the team frequently references the Current State Process Flow Map and root cause analysis when discussing process issues. A peer manager whose improvement initiative failed after 3 months asks: \u201CWhy did your improvements stick while mine faded?\u201D Based on Module 2\u2019s teaching about investigation value, what\u2019s the MOST accurate explanation?",
        options: [
          { label: "A", text: "Your team was more committed to continuous improvement than the other manager\u2019s team" },
          { label: "B", text: "You selected a simpler problem that was easier to sustain than the other manager\u2019s complex problem" },
          { label: "C", text: "Systematic investigation through Sessions #1-6 created shared team understanding of current state, pain points, and root causes, building ownership and capability that sustains improvements\u2014whereas jumping to solutions without investigation creates manager-dependent improvements that fade when attention shifts" },
          { label: "D", text: "You implemented better Control Plans and monitoring systems than the other manager" },
        ],
        correctAnswer: "C",
      },
      {
        id: 17,
        lessonRef: "Module 2 General Knowledge",
        question: "During your Waste WAR Battle investigation phase, you complete all 6 sessions systematically. A senior leader reviewing your progress says: \u201CThis seems like excessive analysis. Why not just fix the obvious problems and move on?\u201D According to Module 2\u2019s teaching about investigation thoroughness, what\u2019s the BEST response?",
        options: [
          { label: "A", text: "You\u2019re right\u2014we could probably skip some sessions to accelerate implementation" },
          { label: "B", text: "The 6-session structure is required by the methodology and cannot be modified" },
          { label: "C", text: "Systematic investigation prevents the common mistake of treating symptoms while root causes persist\u2014Session #5\u2019s pain points included non-obvious issues stakeholders identified that we would have missed, and Session #6\u2019s Cause Tree Analysis revealed deeper causes beneath \u2018obvious\u2019 first-level explanations, ensuring solutions address actual causes not surface symptoms" },
          { label: "D", text: "We\u2019re building team engagement through participation even though investigation probably won\u2019t reveal new information" },
        ],
        correctAnswer: "C",
      },
      {
        id: 18,
        lessonRef: "Module 2 General Knowledge",
        question: "You\u2019re facilitating Session #5 pain point identification with 15 stakeholders including 3 customers. During pain point capture, customers describe frustrations with the process that surprise your team. Your team didn\u2019t identify these pain points during Sessions #3-4. According to Module 2\u2019s emphasis on Voice of Customer in Session #5, what does this scenario demonstrate?",
        options: [
          { label: "A", text: "Your team failed to observe the process thoroughly during Sessions #3-4" },
          { label: "B", text: "Customers misunderstand the process and their concerns aren\u2019t valid pain points" },
          { label: "C", text: "These customer concerns should have been identified during Module 1 SIPOC customer analysis" },
          { label: "D", text: "Voice of Customer in Session #5 reveals pain points invisible to process performers\u2014customers experience different pain points than employees executing the process, making customer participation essential for comprehensive pain point identification and ultimately customer-focused solutions" },
        ],
        correctAnswer: "D",
      },
      {
        id: 19,
        lessonRef: "Module 2 General Knowledge",
        question: "After completing Session #6 root cause analysis, your team has identified 42 root causes across 6 prioritized pain points. A team member says: \u201CIf we only address 6-8 root causes, won\u2019t the other 34 cause the problem to persist?\u201D Based on Module 2\u2019s teaching about root cause prioritization and the CI Done Right Formula sequence, what\u2019s the BEST response?",
        options: [
          { label: "A", text: "You\u2019re right\u2014we should brainstorm solutions for all 42 root causes to ensure complete problem elimination" },
          { label: "B", text: "Addressing 6-8 high-impact root causes typically eliminates 70-80% of the problem because root causes have disproportionate impact (Pareto Principle)\u2014we\u2019ll measure improvement after implementing solutions to the prioritized root causes, and if problems persist we\u2019ll conduct another Waste WAR Battle addressing remaining causes; solving everything in one initiative is unrealistic" },
          { label: "C", text: "We\u2019ll document all 42 root causes and address them gradually over the next 2-3 years through continuous improvement" },
          { label: "D", text: "The other 34 root causes are low-impact so eliminating them won\u2019t significantly reduce the problem" },
        ],
        correctAnswer: "B",
      },
      {
        id: 20,
        lessonRef: "Module 2 General Knowledge",
        question: "Looking back on your completed Module 2 investigation (Sessions #1-6), you realize that Sessions #3-6 consumed significantly more time than Sessions #1-2. A time-conscious stakeholder asks: \u201CWhy did Steps 3-4 require 4 sessions while Steps 1-2 only needed 2 sessions?\u201D Based on Module 2\u2019s lesson structure and investigation methodology, what\u2019s the MOST accurate explanation?",
        options: [
          { label: "A", text: "Steps 1-2 are less important than Steps 3-4 so less time is appropriate" },
          { label: "B", text: "The lesson designer made the later sessions longer to maintain participant engagement over 6 weeks" },
          { label: "C", text: "Steps 3-4 (current state confirmation and pain point/root cause analysis) involve more complex team activities requiring more session time\u2014Session #3 requires actual process observation, Session #4 requires collaborative process mapping, Session #5 requires expanded stakeholder participation for pain point identification and PICK Chart prioritization, Session #6 requires Cause Tree Analysis for multiple pain points and root cause prioritization; whereas Steps 1-2 primarily involve metric definition and planning activities requiring less collaborative work time" },
          { label: "D", text: "The time allocation is arbitrary and could be redistributed without affecting investigation quality" },
        ],
        correctAnswer: "C",
      },
    ],
  },
  {
    moduleNumber: 3,
    title: "Intelligently Testing Potential Solutions",
    passThreshold: 80,
    questions: [
      { id: 1, lessonRef: "Lesson 1", question: "During Session #7 zero constraints visioning exercise, a team member suggests automating the entire initial review using AI. Another team member immediately responds that it\u2019s unrealistic due to budget and approval constraints. According to this lesson\u2019s teaching on zero constraints visioning, how should you facilitate this moment?", options: [{ label: "A", text: "Agree with the second team member that AI is unrealistic and redirect to more feasible ideas" }, { label: "B", text: "Interrupt the constraint, remind the team they\u2019re in zero constraints mode where budget and approval are unlimited, ask the first team member to elaborate on the AI automation vision, and explain constraints will be assessed later" }, { label: "C", text: "Take a vote on whether AI automation should be included in the vision" }, { label: "D", text: "Table the AI discussion until Session #8 solution brainstorming" }], correctAnswer: "B" },
      { id: 2, lessonRef: "Lesson 1", question: "Your team has completed Session #7 and created a Future State Paragraph. When you review it, you find vague statements like: \u201CApplications will be processed faster,\u201D \u201CWe\u2019ll have fewer errors,\u201D \u201CCustomers will be happier.\u201D According to this lesson\u2019s teaching on Future State Paragraph requirements, what is the problem?", options: [{ label: "A", text: "It\u2019s too short and needs more detail about team member roles" }, { label: "B", text: "It uses vague unmeasurable aspirations instead of specific quantified targets; it should state measurable improvements like \u201C8-hour processing from current 3-5 days,\u201D \u201Cunder 3% error rate from current 12%,\u201D \u201C95% customer satisfaction from current 67%\u201D" }, { label: "C", text: "It focuses too much on outcomes and doesn\u2019t describe process flow changes" }, { label: "D", text: "It needs to be reformatted as a process flow map instead" }], correctAnswer: "B" },
      { id: 3, lessonRef: "Lesson 2", question: "During Session #8 solution generation, a team member suggests automating initial application screening using AI. Another team member immediately criticizes the idea as too expensive. According to this lesson\u2019s teaching on brainstorming best practices, how should you facilitate this moment?", options: [{ label: "A", text: "Agree that the AI solution is probably too expensive and move to the next idea" }, { label: "B", text: "Interrupt the criticism, remind the team they\u2019re in generation mode where all ideas get captured without evaluation, have the scribe record the AI automation idea, and redirect to generating more solutions" }, { label: "C", text: "Pause generation to debate whether AI automation is feasible" }, { label: "D", text: "Ask the team to vote on whether to include the AI solution" }], correctAnswer: "B" },
      { id: 4, lessonRef: "Lesson 2", question: "Your team is brainstorming solutions during Session #8. After 8 minutes of generation, they\u2019ve identified 4 potential solutions and seem satisfied. According to this lesson\u2019s teaching on brainstorming best practices, what should you do?", options: [{ label: "A", text: "Proceed to PICK Chart prioritization since the team has solutions to evaluate" }, { label: "B", text: "Push for additional ideas by reminding them of the quantity target (10-15 solutions minimum), using creative prompts, and continuing generation for the full 15 minutes" }, { label: "C", text: "Compromise by generating 2 more solutions to reach 6 total" }, { label: "D", text: "Accept the 4 solutions but ask each to be explained in more detail" }], correctAnswer: "B" },
      { id: 5, lessonRef: "Lesson 3", question: "Sessions #8-9 produced 36 solutions total. During final prioritization, 13 solutions land in the Implement quadrant. According to this lesson\u2019s teaching on final prioritization, what should you do?", options: [{ label: "A", text: "Test all 13 Implement quadrant solutions since they\u2019re all high-value" }, { label: "B", text: "Select the maximum 8 solutions from the Implement quadrant based on highest combined impact and ease scores, explaining that 8 solutions enable 45 min/solution testing across Sessions #10-13 versus 13 solutions enabling only 28 min/solution" }, { label: "C", text: "Expand testing timeline to accommodate all 13 solutions" }, { label: "D", text: "Have team vote on which to keep" }], correctAnswer: "B" },
      { id: 6, lessonRef: "Lesson 3", question: "During Session #9 final prioritization, your team identifies that three separate solutions from different root causes are actually complementary and would be more effective implemented together. According to this lesson\u2019s teaching on combination solutions, how should you handle this?", options: [{ label: "A", text: "Treat them as three separate solutions consuming three of the eight testing slots" }, { label: "B", text: "Consider whether the three complementary solutions can be combined into a single comprehensive solution package consuming one testing slot, enabling more sophisticated solution within the 8-solution constraint while addressing multiple root causes" }, { label: "C", text: "Eliminate all three solutions to avoid complexity" }, { label: "D", text: "Test only the easiest of the three solutions" }], correctAnswer: "B" },
      { id: 7, lessonRef: "Lesson 4", question: "A Trial Implementation Group plans to spend $35,000 and 8 weeks building complete system integration, then measure whether it solves the identified root cause. According to this lesson\u2019s teaching on quick/inexpensive testing philosophy, what is the problem?", options: [{ label: "A", text: "The timeline is too short; they should extend to 12 weeks" }, { label: "B", text: "This violates quick/inexpensive philosophy by treating trial as full implementation; recommend a lightweight alternative that simulates the integration concept inexpensively to validate viability before committing $35K" }, { label: "C", text: "The budget is appropriate but they need more specific measurement metrics" }, { label: "D", text: "Nothing is wrong; comprehensive integration testing requires significant investment" }], correctAnswer: "B" },
      { id: 8, lessonRef: "Lesson 4", question: "During Session #10, eight Trial Implementation Groups work simultaneously developing their solution plans. According to this lesson\u2019s teaching on parallel group work facilitation, what is the appropriate approach?", options: [{ label: "A", text: "Focus on helping the 2-3 groups with the most complex solutions" }, { label: "B", text: "Systematically rotate among all 8 groups spending approximately 8-9 minutes per group per rotation cycle, completing 2 rotation cycles during the 70 minutes; during visits review plans, answer questions, ensure quick/inexpensive philosophy followed" }, { label: "C", text: "Have all groups present their draft plans simultaneously every 20 minutes for whole-team feedback" }, { label: "D", text: "Develop all 8 plans yourself while groups observe" }], correctAnswer: "B" },
      { id: 9, lessonRef: "Lesson 5", question: "A Trial Implementation Group presents their Session #11 progress report: \u201COur trial is going really well. The team seems much happier and things feel more efficient.\u201D According to this lesson\u2019s teaching on evidence-focused reporting, what is the problem?", options: [{ label: "A", text: "This is a good report showing the trial is successful" }, { label: "B", text: "This report lacks evidence focus\u2014it contains opinions and feelings without observations or data; probe for specifics about what data supports their claims and what measurements they\u2019ve collected" }, { label: "C", text: "Accept the positive report but ask for more detail about implementation steps" }, { label: "D", text: "Request the group provide a written report with more information" }], correctAnswer: "B" },
      { id: 10, lessonRef: "Lesson 5", question: "During Session #11, a Trial Implementation Group reports significant challenges and requests 30 minutes of full team time to brainstorm solutions. Six other groups are still waiting to present. According to this lesson\u2019s teaching on time discipline, what should you do?", options: [{ label: "A", text: "Grant the 30 minutes since solving problems is the session\u2019s purpose" }, { label: "B", text: "Acknowledge the challenges, facilitate 2-3 minutes of quick team input capturing key suggestions, then defer detailed problem-solving to between sessions so all groups can report on schedule" }, { label: "C", text: "Skip the remaining group presentations to fully solve this group\u2019s problem" }, { label: "D", text: "Tell the group to figure out their problems independently without any team input" }], correctAnswer: "B" },
      { id: 11, lessonRef: "Lesson 6", question: "During Session #12, Trial Group A reports a 62.5% improvement based on three employees processing nine transactions over one week. They want to implement immediately. According to this lesson\u2019s teaching on statistical validation, what should you do?", options: [{ label: "A", text: "Celebrate and recommend immediate full implementation" }, { label: "B", text: "Discount the result entirely as statistically meaningless" }, { label: "C", text: "Acknowledge the encouraging preliminary result while explaining that additional validation is needed\u2014expand to more employees and more transactions over the remaining testing weeks to confirm the improvement is repeatable and sustainable, not just fortunate variation" }, { label: "D", text: "Have the same three employees repeat the exact same trial to verify" }], correctAnswer: "C" },
      { id: 12, lessonRef: "Lesson 6", question: "During Session #12 comparative analysis, some Trial Groups had smooth implementation while others faced resistance. Successful groups pre-engaged stakeholders before launch, while struggling groups did not. According to this lesson\u2019s teaching on comparative analysis, what should you do?", options: [{ label: "A", text: "Congratulate successful groups and continue without further discussion" }, { label: "B", text: "Facilitate explicit cross-trial learning by highlighting stakeholder engagement as best practice all trials should adopt; recommend struggling groups conduct stakeholder meetings before continuing; document this as standard practice for future Waste WAR Battles" }, { label: "C", text: "Criticize the struggling groups for poor planning" }, { label: "D", text: "Conclude that successful groups simply had superior solutions" }], correctAnswer: "B" },
      { id: 13, lessonRef: "Lesson 7", question: "During Session #13 final selection, Solution A showed consistent improvement: 32%, 35%, 36%. Solution B showed declining improvement: 48%, 38%, 35%. Both achieved 35% in the final iteration. According to this lesson\u2019s validated improvement criterion teaching, how should you evaluate?", options: [{ label: "A", text: "Both solutions are equal since final results are identical at 35%" }, { label: "B", text: "Solution A demonstrates validated improvement with consistent/improving trend indicating sustainable performance; Solution B shows concerning declining trend raising questions about sustainability despite a strong start; Solution A is the stronger candidate" }, { label: "C", text: "Solution B is superior due to highest single-iteration result (48%)" }, { label: "D", text: "Average all three iterations making both solutions approximately equal" }], correctAnswer: "B" },
      { id: 14, lessonRef: "Lesson 7", question: "During Session #13 business case review, a group presents excellent quantified results (200:1 ROI, 45% validated improvement) but has an incomplete implementation roadmap and superficial risk mitigation. According to this lesson\u2019s business case review teaching, what should you do?", options: [{ label: "A", text: "Accept the business case since ROI is compelling" }, { label: "B", text: "Identify specific gaps requiring strengthening before leadership presentation: add specific phase timelines, resource requirements, milestones for the roadmap, and identify top 3 implementation risks with specific evidence-based mitigation strategies from trial experience" }, { label: "C", text: "Present the incomplete business case to leadership to see their questions" }, { label: "D", text: "Reject the solution entirely due to incomplete business case" }], correctAnswer: "B" },
      { id: 15, lessonRef: "Module 3 General Knowledge", question: "After completing Module 3, a colleague asks: \u201CWhat\u2019s the main difference between Module 2 (Investigating Root Causes) and Module 3 (Intelligently Testing Potential Solutions)?\u201D Based on Module 3\u2019s comprehensive teaching, what\u2019s the BEST answer?", options: [{ label: "A", text: "Module 2 focuses on problems while Module 3 focuses on solutions, so Module 3 is more positive and easier" }, { label: "B", text: "Module 2 requires data collection while Module 3 is purely conceptual brainstorming without measurement" }, { label: "C", text: "Module 2 investigates WHY problems exist through systematic root cause analysis (Sessions #1-6), while Module 3 intelligently tests HOW to solve them through structured methodology: defining ideal future state, brainstorming solutions, and rigorously testing through three-iteration PDCA trials before implementing" }, { label: "D", text: "Module 2 is completed by the manager alone while Module 3 requires full team participation" }], correctAnswer: "C" },
      { id: 16, lessonRef: "Module 3 General Knowledge", question: "Six months after completing your first Waste WAR Battle using Module 3\u2019s testing methodology, your solution is performing exactly as predicted. A peer manager whose initiative failed after 2 months asks why your solution stuck. Based on Module 3\u2019s teaching, what\u2019s the MOST accurate explanation?", options: [{ label: "A", text: "Your problem was simpler" }, { label: "B", text: "You had more committed team members" }, { label: "C", text: "Module 3\u2019s three-iteration PDCA testing methodology validated solution effectiveness before full implementation through systematic experimentation\u2014each iteration refined approach based on data, identified obstacles, confirmed consistency, built stakeholder support, and developed deployment expertise; solutions validated through disciplined testing succeed 90% of the time versus 30% when skipping validation" }, { label: "D", text: "You were fortunate to select the right solution on first try" }], correctAnswer: "C" },
      { id: 17, lessonRef: "Module 3 General Knowledge", question: "Session #13 comparative analysis reveals Solution A achieved 42% improvement across three consistent iterations. A team member argues to implement it immediately. According to Module 3\u2019s teaching about comprehensive solution selection, what should you consider?", options: [{ label: "A", text: "Agree that 42% improvement makes Solution A the obvious choice" }, { label: "B", text: "Select a lower-performing solution since it\u2019s \u201Cgood enough\u201D" }, { label: "C", text: "Consider multiple selection criteria beyond performance: implementation complexity, resource requirements, strategic fit, and risk profile; sometimes a solution with slightly lower performance but significantly easier implementation provides better overall organizational value" }, { label: "D", text: "Reject all solutions since none achieved the ideal future state" }], correctAnswer: "C" },
      { id: 18, lessonRef: "Module 3 General Knowledge", question: "After testing, you notice the 8 selected solutions came from only 3 of 8 prioritized root causes. A team member worries the problem will persist. According to Module 3\u2019s teaching, what\u2019s the BEST response?", options: [{ label: "A", text: "Acknowledge failure and restart the Waste WAR Battle" }, { label: "B", text: "Explain that addressing 3 of 8 root causes typically eliminates 60-80% of the problem due to the Pareto Principle; if implemented solutions achieve metric targets, the Waste WAR Battle succeeded; if significant problems remain, conduct a subsequent Waste WAR Battle" }, { label: "C", text: "Immediately expand testing to include all 8 root causes" }, { label: "D", text: "Blame the facilitator for poor prioritization" }], correctAnswer: "B" },
      { id: 19, lessonRef: "Module 3 General Knowledge", question: "During Session #8 brainstorming, a team member suggests a procedural solution and another immediately criticizes it saying procedures failed in 2018. According to Module 3\u2019s teaching, what does this demonstrate and how should you respond?", options: [{ label: "A", text: "The criticism is valid\u2014if procedures failed before, they won\u2019t work now" }, { label: "B", text: "This demonstrates a brainstorming best practice violation: criticism during generation mode kills creativity; interrupt the criticism, remind the team they\u2019re in generation mode, record the idea, and redirect to generating more solutions; evaluation comes later" }, { label: "C", text: "Cancel brainstorming and return to Session #6" }, { label: "D", text: "Take a vote on whether to include the idea" }], correctAnswer: "B" },
      { id: 20, lessonRef: "Module 3 General Knowledge", question: "A time-conscious stakeholder suggests reducing testing from 4 weeks to 2 weeks. According to Module 3\u2019s teaching about rigorous testing, what\u2019s the MOST accurate response?", options: [{ label: "A", text: "Agree that 2-week testing would be more efficient" }, { label: "B", text: "Explain that 4-week three-iteration testing is the minimum rigorous validation timeline: each week\u2019s iteration confirms or contradicts prior results, enabling statistical confidence; reducing to 2 weeks eliminates validation rigor that distinguishes professional testing from trial-and-error; the 2-week \u201Csavings\u201D creates risk of implementing an inferior solution" }, { label: "C", text: "Propose a 3-week compromise" }, { label: "D", text: "Suggest eliminating testing entirely since brainstorming already identified the best solutions" }], correctAnswer: "B" },
    ],
  },
  {
    moduleNumber: 4,
    title: "Implementing Winning Solutions for Success",
    passThreshold: 80,
    questions: [
      { id: 1, lessonRef: "Lesson 1", question: "A Winning Solution showed 45% cycle time improvement during trials. Your team proposes skipping phased deployment and implementing organization-wide immediately. According to this lesson\u2019s teaching on phased deployment, what is the problem?", options: [{ label: "A", text: "Immediate organization-wide deployment is ideal since the solution is validated" }, { label: "B", text: "Phased deployment is critical even for validated solutions because it manages implementation risk systematically through training phases, broader expansion, full deployment, and sustainability monitoring; skipping phases risks implementation failures" }, { label: "C", text: "Only struggling solutions require phased approach; validated solutions can deploy immediately" }, { label: "D", text: "Phased deployment is optional based on organizational culture" }], correctAnswer: "B" },
      { id: 2, lessonRef: "Lesson 1", question: "During Session #14 Control Plan development, a team documents SOPs and assigns a process owner but doesn\u2019t establish an ongoing measurement system or audit/review schedule. According to this lesson\u2019s teaching on Control Plans, what is missing?", options: [{ label: "A", text: "Nothing missing\u2014SOPs and process owner are sufficient" }, { label: "B", text: "Two critical components: (1) Ongoing measurement system for sustainable automated/low-effort monitoring replacing trial\u2019s manual tracking, and (2) Audit/review schedule with weekly spot checks, monthly performance reviews, quarterly comprehensive assessments creating accountability" }, { label: "C", text: "Measurement systems are unnecessary after successful implementation" }, { label: "D", text: "Audit schedules create unnecessary bureaucracy" }], correctAnswer: "B" },
      { id: 3, lessonRef: "Lesson 2", question: "You\u2019re 15 days into a new manager role. Your boss mentions customer complaints about 4-day processing times. Your team suggests a 9-month, $50K technology project. According to this lesson\u2019s quick win strategy, what should you do?", options: [{ label: "A", text: "Immediately launch the 9-month, $50K technology project" }, { label: "B", text: "Identify a quick win within the problem using Module 1 tools to find a smaller improvement achievable in 30-45 days with minimal resources, build credibility first, then position the technology project as Phase 2" }, { label: "C", text: "Tell boss you need to wait until Day 60 since you\u2019re still assessing" }, { label: "D", text: "Tell boss nothing can be done without the $50K investment" }], correctAnswer: "B" },
      { id: 4, lessonRef: "Lesson 2", question: "During your first 30 days you\u2019ve identified 12 improvement opportunities. Your boss expects to see impact by Day 60. According to this lesson\u2019s teaching on prioritization, how should you proceed?", options: [{ label: "A", text: "Launch all 12 improvements simultaneously" }, { label: "B", text: "Select 1-2 that meet all five quick win criteria (achievable in 30-45 days, minimal resources, recognized pain point, visible to stakeholders, demonstrates capability), execute those successfully, save remaining opportunities for later prioritization using full Waste WAR Battle methodology" }, { label: "C", text: "Wait until comprehensive analysis of all 12 is complete, even past Day 60" }, { label: "D", text: "Let team members vote on which to pursue" }], correctAnswer: "B" },
      { id: 5, lessonRef: "Lesson 3", question: "Three months after a successful Waste WAR Battle (40% cycle time reduction), you notice employees reverting to old methods and cycle time has increased back to 3.8 days. According to this lesson\u2019s teaching on culture reinforcement, what\u2019s the root cause?", options: [{ label: "A", text: "The solution wasn\u2019t effective; start a new Waste WAR Battle" }, { label: "B", text: "Missing Culture Reinforcement System components: no daily Waste Warrior exercises, no weekly check-ins, no visual management dashboard; implement systematic reinforcement to transform temporary change into permanent habit" }, { label: "C", text: "Team members are lazy; apply disciplinary action" }, { label: "D", text: "Control Plans were inadequate; re-write them" }], correctAnswer: "B" },
      { id: 6, lessonRef: "Lesson 3", question: "You want to recognize three Waste Warriors with different recognition preferences: one loves public recognition, one prefers private acknowledgment, one values development opportunities. According to this lesson\u2019s teaching on recognition strategies, what\u2019s the most effective approach?", options: [{ label: "A", text: "Recognize all three publicly for fairness and consistency" }, { label: "B", text: "Apply recognition matching individual preferences: public recognition for the first, private appreciation for the second, and development opportunities for the third; meaningful rewards align with individual motivations" }, { label: "C", text: "Don\u2019t recognize anyone to avoid complexity" }, { label: "D", text: "Give everyone the same certificate" }], correctAnswer: "B" },
      { id: 7, lessonRef: "Lesson 4", question: "Your boss suggests you facilitate a Waste WAR Battle for a peer department. According to this lesson\u2019s teaching on internal consulting, how should you approach this?", options: [{ label: "A", text: "Decline because consulting should only be external" }, { label: "B", text: "Accept as valuable internal consulting opportunity: negotiate positioning as development assignment, deliver professional facilitation, meticulously document results for your portfolio, secure a testimonial upon completion, and position for additional consulting requests; internal consulting provides low-risk practice before external practice launch" }, { label: "C", text: "Accept only if the peer department pays full external rates" }, { label: "D", text: "Facilitate for free without any formal structure" }], correctAnswer: "B" },
      { id: 8, lessonRef: "Lesson 4", question: "A potential external client asks about consulting pricing for a Waste WAR Battle engagement estimated to save them $150,000 annually, requiring ~80 hours over 16 weeks. According to this lesson\u2019s teaching on value-based pricing, what approach should you use?", options: [{ label: "A", text: "Charge hourly rate ($200/hour \u00d7 80 hours = $16,000)" }, { label: "B", text: "Use value-based pricing: propose $20,000-25,000 (13-17% of annual savings), positioned as an investment generating 6-7x ROI in year one, aligning your fee with value delivered rather than hours invested" }, { label: "C", text: "Charge a flat $30,000 fee regardless of value creation" }, { label: "D", text: "Offer free initial engagement to build portfolio" }], correctAnswer: "B" },
      { id: 9, lessonRef: "Module 4 General Knowledge", question: "A colleague who completed Module 3 asks: \u201CWhat\u2019s the main difference between Module 3 and Module 4?\u201D Based on Module 4\u2019s comprehensive teaching, what\u2019s the BEST answer?", options: [{ label: "A", text: "Module 3 focuses on testing while Module 4 focuses on implementation, so they\u2019re essentially the same at different scales" }, { label: "B", text: "Module 3 requires team participation while Module 4 is executed by the manager alone" }, { label: "C", text: "Module 3 rigorously tests solutions through PDCA trials to identify the winning solution, while Module 4 implements it and ensures long-term success through structured deployment, maximizing first 100 days in new assignments, building self-sustaining improvement culture, and optionally monetizing CI expertise through consulting" }, { label: "D", text: "Module 3 teaches technical methods while Module 4 teaches only soft skills" }], correctAnswer: "C" },
      { id: 10, lessonRef: "Module 4 General Knowledge", question: "You\u2019ve completed the entire 25-lesson Masterclass. A skeptical peer says: \u201CWhy not just identify a problem and implement a solution quickly instead of spending 14 weeks on systematic methodology?\u201D Based on the complete Masterclass teaching, what\u2019s the MOST compelling response?", options: [{ label: "A", text: "The 14-week timeline is industry standard" }, { label: "B", text: "Complicated methodology impresses senior leadership" }, { label: "C", text: "The CI Done Right Formula prevents the three failure modes that destroy 70% of improvement initiatives: symptom treatment (Modules 1-2 ensure root cause solutions), untested assumptions (Module 3 validates before implementing), and degradation/regression (Module 4 sustains improvements). Quick \u2018identify and implement\u2019 succeeds 30% of the time. Systematic methodology succeeds 90% of the time." }, { label: "D", text: "We use systematic methodology because it\u2019s what the training course taught us" }], correctAnswer: "C" },
    ],
  },
];
